variable "name" {}
variable "env" {}
variable "subnet_ids" {}
variable "tags" {}
variable "vpc_id" {}
variable "port_no" {}
variable "allow_db_cidr" {}
variable "engine_version" {}
variable "kms_arn" {}
variable "num_node_groups" {}
variable "node_type" {}
variable "replicas_per_node_group" {}